export enum AppErrorCode {
    //user errors
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    EMAIL_EXISTS = 'EMAIL_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
    ACCOUNT_ALREADY_ACTIVE = 'ACCOUNT_ALREADY_ACTIVE',
    INVALID_CODE = 'INVALID_CODE',
    CODE_EXPIRED = 'CODE_EXPIRED',
    PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',

    //word errors
    WORD_NOT_FOUND = 'WORD_NOT_FOUND',

    //topic errors
    TOPIC_NOT_FOUND = 'TOPIC_NOT_FOUND',

    //example errors
    EXAMPLE_NOT_FOUND = 'EXAMPLE_NOT_FOUND',

    //learning errors
    WORD_ALREADY_IN_LIST = 'WORD_ALREADY_IN_LIST',
    LEARNING_ENTRY_NOT_FOUND = 'LEARNING_ENTRY_NOT_FOUND',
}
